# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170331_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
